language: node_js

node_js:
  - stable

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

install:
  - npm install

script:
  # publish the package
  - npm run build:new
  - npm run publish
  # install the latest version of "openapi-generator-cli"
  - npm install @openapitools/openapi-generator-cli -g
  - openapi-generator version
  - npm uninstall @openapitools/openapi-generator-cli -g
  # install a specific version of "openapi-generator-cli"
  - npm install @openapitools/openapi-generator-cli@cli-3.2.1 -g
  - openapi-generator version
  - npm uninstall @openapitools/openapi-generator-cli@cli-3.2.1 -g
  # install the latest version of "openapi-generator-cli" (package mode)
  - cd /tmp/ && npm install @openapitools/openapi-generator-cli -D
