os: linux
cache: yarn
dist: xenial
language: node_js

jobs:
  include:
    - stage: test
      name: "Lint"
      script: yarn run lint

    - # stage name not required, will continue to use `test`
      name: "Test"
      script: yarn test

    - # stage name not required, will continue to use `test`
      name: "Integration test (simple)"
      script:
        - yarn run build
        - mkdir tmp
        - cd dist/apps/generator-cli
        - yarn pack -f ../../../tmp/generator-cli.tgz
        - cd ../../../tmp
        - tar zxvf generator-cli.tgz
        - chmod +x package/main.js
        - package/main.js version
        - package/main.js help
        - package/main.js help generate
        - package/main.js wont work

    - stage: deploy
      if: type IN (push) and branch IN (master)
      name: "Build & Deploy"
      script:
        - yarn run build
