os: linux
cache: yarn
dist: xenial
language: node_js

jobs:
  include:
    - stage: test
      name: "Lint"
      script: yarn run lint

    - # stage name not required, will continue to use `test`
      name: "Unit test"
      script: yarn test

    - # stage name not required, will continue to use `test`
      name: "Integration test (simple)"
      script:
        - yarn run build
        - cd dist/apps/generator-cli
        - yarn pack -f ../generator-cli.tgz
        - mkdir ~/generator-cli-integration-test && cd "$_"
        - yarn init -y
        - yarn add $TRAVIS_BUILD_DIR/dist/apps/generator-cli.tgz
        - ./node_modules/.bin/openapi-generator-cli version
        - ./node_modules/.bin/openapi-generator-cli help
        - ./node_modules/.bin/openapi-generator-cli help generate

    - stage: deploy
      if: type IN (push) and branch IN (master)
      name: "Build & Deploy"
      script:
        - yarn run build
