os: linux
cache: yarn
dist: xenial
language: shell

jobs:
  include:
    - stage: test
      name: "Lint"
      language: node_js
      script: npm run lint

    - # stage name not required, will continue to use `test`
      name: "Test"
      language: node_js
      script: npm run nx -- test

    - stage: deploy
      if: type IN (push) and branch IN (master, develop)
      name: "Build & Deploy"
      os: osx
      language: node_js
      script:
        - npm run nx -- build generator-cli --prod --webpack-config ./apps/generator-cli/webpack.config.js
        - mv $TRAVIS_BUILD_DIR/dist/apps/api/package.json $TRAVIS_BUILD_DIR/dist/package.json
        - terraform init $tf_init_cli_options
        - terraform workspace select $tf_workspace
        - terraform apply $tf_apply_cli_options
