os: linux
cache: yarn
dist: xenial
language: node_js

jobs:
  include:
    - stage: test
      name: "Lint"
      script: yarn run lint

    - # stage name not required, will continue to use `test`
      name: "Unit test"
      script: yarn test

    - # stage name not required, will continue to use `test`
      name: "Integration test (simple)"
      script:
        - yarn run build
        - cd dist/apps/generator-cli
        - yarn pack -f ../generator-cli.tgz
        - mkdir ~/generator-cli-integration-test && cd "$_"
        - ls -la
        - yarn init -y
        - yarn add $TRAVIS_BUILD_DIR/dist/apps/generator-cli.tgz
        - ./node_modules/.bin/openapi-generator-cli version
        - ./node_modules/.bin/openapi-generator-cli help
        - ./node_modules/.bin/openapi-generator-cli help generate
        - ./node_modules/.bin/openapi-generator-cli version-manager help
        - (./node_modules/.bin/openapi-generator-cli version-manager set 3.0.0 && node ./node_modules/.bin/openapi-generator-cli version | grep -q '3.0.0') || exit 1
        - (./node_modules/.bin/openapi-generator-cli version-manager set 4.0 && node ./node_modules/.bin/openapi-generator-cli version | grep -q '4.0.3') || exit 1
        - (./node_modules/.bin/openapi-generator-cli version-manager set 4.3.1 && node ./node_modules/.bin/openapi-generator-cli version | grep -q '4.3.1') || exit 1

    - stage: deploy
      if: type IN (push) and branch IN (master)
      name: "Build & Deploy"
      script:
        - yarn run build
