os: linux
cache: yarn
dist: xenial
language: node_js

jobs:
  include:
    - stage: test
      name: "Lint"
      script: yarn run lint

    - # stage name not required, will continue to use `test`
      name: "Test"
      script: yarn test

    - stage: deploy
      if: type IN (push) and branch IN (master)
      name: "Build & Deploy"
      script:
        - yarn run build
