name: Build
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version }}

      - name: Install
        run: npm i --from-lockfile

      - name: Lint
        run: yarn run lint

      - name: Unit Test
        run: yarn run test

      - name: Build
        run: yarn run build

      - name: Build Package
        run: |
          cd dist/apps/generator-cli
          yarn pack -f ../package.tgz

      - uses: actions/upload-artifact@v2
        with:
          name: package.tgz
          path: dist/apps/package.tgz

  e2e:
    name: E2E (${{ matrix.os }})
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version }}

      - uses: actions/download-artifact@v2
        with:
          name: package.tgz

      - name: Test
        run: |
          mkdir ~/generator-cli-integration-test && cd "$_"
          yarn init -y
          yarn cache clean && yarn add $GITHUB_WORKSPACE/package.tgz
          ./node_modules/.bin/openapi-generator-cli version
          ./node_modules/.bin/openapi-generator-cli completion
          ./node_modules/.bin/openapi-generator-cli help
          ./node_modules/.bin/openapi-generator-cli help generate
          ./node_modules/.bin/openapi-generator-cli version-manager help
          ./node_modules/.bin/openapi-generator-cli generate -g ruby -i https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml -o $GITHUB_WORKSPACE/tmp/ruby-client
          (./node_modules/.bin/openapi-generator-cli version-manager set 3.0.0 && node ./node_modules/.bin/openapi-generator-cli version | grep -q '3.0.0') || exit 1
          (./node_modules/.bin/openapi-generator-cli version-manager set 4.0 && node ./node_modules/.bin/openapi-generator-cli version | grep -q '4.0.3') || exit 1
          (./node_modules/.bin/openapi-generator-cli version-manager set 4.3.1 && node ./node_modules/.bin/openapi-generator-cli version | grep -q '4.3.1') || exit 1
          (./node_modules/.bin/openapi-generator-cli version-manager set 4.3.1 && node ./node_modules/.bin/openapi-generator-cli version | grep -q '4.3.1') || exit 1
          cp -r $GITHUB_WORKSPACE/examples ./examples
          rm openapitools.json && mv ./examples/openapitools.json ./openapitools.json && ./node_modules/.bin/openapi-generator-cli generate
